# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baaf89d2ab90399f002ba6499f1936ac7511e4f8b0bb4fe3ef916838475235d84c703f46b81a734b51189138927c25cf6ef754898d024972ad83f6c2e8f5b7d2

test:
  secret_key_base: bc0b559eeef24b3ed747e56d174067d6afe3982608e477e8ec1a65dcf1aca6e36da42560dfd5d4478e77dfd1ac79ea926234360fb9cd0be55013a15837235c0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
